Removed the Version from the webjars-locator-core, dependency
uhawaii-system-its-ti-iam/uh-groupings-ui pull request #514
Opened 2022-02-04 02:16 UTC by buccatm

[Ticket #1019](https://www.hawaii.edu/jira/secure/RapidBoard.jspa?rapidView=100&projectKey=GROUPINGS&view=detail&selectedIssue=GROUPINGS-1019&quickFilter=222)

2022-02-04 02:41 UTC, mhodgesatuh commented
Added Kobey as a reviewer, our emerging standard practice for this branch.

2022-02-04 07:07 UTC, Kobeyarai808 requested changes
Change looks good, did this pass unit tests and visual inspection?

2022-02-08 00:08 UTC, buccatm commented
Had ran Unit test on the ui and api side. There was no error or failures reported from the test.

2022-02-08 01:59 UTC, Kobeyarai808 approved these changes

2022-02-08 01:59 UTC, merged