Create README for badges Branch
uhawaii-system-its-ti-iam/uh-groupings-ui pull request #581
Opened 2022-05-04 03:33 UTC by Erick-Orozco-Ciprian

# Ticket Link

[Ticket](https://www.hawaii.edu/jira/browse/GROUPINGS-1094)

# List of squashed commits

- Created README

# Test Checklist

- [ ] General Visual Inspection:

2022-05-04 23:22 UTC, Kobeyarai808 approved these changes
Looks good!

2022-05-04 23:29 UTC, mhodgesatuh requested changes
This branch utilizes Github Actions in order to automatically update status badges
 - You need a period at the end of the above sentence.  Appropriate use of punctuation counts here too.

Below are working examples of the Build and Coverage status badges
 - You need a colon at the end for the same reason as above.

2022-05-05 00:43 UTC, Kobeyarai808 approved these changes
Looks good! Thanks for fixing the punctuation!

2022-05-06 02:58 UTC, devgav approved these changes

2022-05-13 00:51 UTC, merged